version: '2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: "mongoDB"
    network_mode: host
    environment:
      MONGO_INITDB_DATABASE: movieDB

  eureka:
    image: eureka-server
    build: eureka-server/
    network_mode: host
    container_name: "eureka-server"
    ports:
      - 9090:9090
    expose:
      - 9090

  config:
    image: config-server
    build: config-service/
    network_mode: host
    container_name: "config-server"
    depends_on:
      - eureka
    ports:
      - 8888:8888
    expose:
      - 8888

  movieApp:
    image: movie-service
    build: Movie-Cruiser-App/
    network_mode: host
    container_name: "spring-app"
    depends_on:
      - mongodb
      - eureka
      - config
    ports:
      - 8080:8080
    expose:
      - 8080

  zuul:
    image: api-gateway
    build: zuul-apigateway/
    network_mode: host
    container_name: "api-gateway"
    depends_on:
      - movieApp
    ports:
      - 8081:8081
    expose:
      - 8081
